Doc Appointment/urls.py
from django.urls import path

from . import views
from django.conf.urls import url
# from django.contrib.auth import views as auth

urlpatterns = [
    path('',views.index,name='index'),
    url('create_appointment/', views.create_appointment, name = 'create_appointment'),
	url('register_doctor/', views.register_doctor, name = 'register_doctor'),
	url('register_speciality/', views.register_speciality, name = 'register_specialty'),
	url('see_appointments/', views.appointment_list, name = 'appointment_list'),
	url('create_user/', views.AddingUser),
	url('(?P<pk>[-\d]+)/edit/', views.appointment_edit, name='appointment_edit'),
	url('(?P<pk>[-\d]+)/delete/', views.appointment_delete, name='appointment_delete'),
	url('login/', auth_views.login, {'template_name': 'login.html'}, name='login'),
	url('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),

]

Myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Proj/', include('Proj.urls')),
    path('Doc Appointment/',include('Doc Appointment.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Proj/urls.py
from django.urls import path
from.import views
app_name='Proj' 
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('(?P<pk>[0-9]+)/',views.DetailView.as_view(),name='detail'),
    path('album/add/',views.AlbumCreate.as_view(),name='album-add'),
    path('album/(?P<pk>[0-9]+)/',views.AlbumUpdate.as_view(),name='album-update'),
    path('album/(?P<pk>[0-9]+)/delete/',views.AlbumDelete.as_view(),name='album-delete'),

    ]

Doc Appointment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Doctors(models.Model):
    name = models.CharField(max_length=200)
    speciality = models.CharField(max_length=200)

    class Meta:
         ordering = ('id' ,)
class Speciality(models.Model):
    speciality_name= models.CharField(max_length=200)


class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE , null=True, blank=True )
    doctor =models.CharField(max_length=200)
    description = models.TextField(max_length=20000)
    date = models.DateField(default = 0)

    class Meta:
         ordering = ('id',)

    def __str__(self):
        return self.user.username

Proj/models.py
from django.db import models
from django.urls import reverse
class Album(models.Model):
	artist=models.CharField(max_length=250)
	album_title=models.CharField(max_length=250)
	genre=models.CharField(max_length=250)
	album_logo=models.FileField()
	def get_absolute_url(self):
		return reverse('Proj:detail',kwargs={'pk':self.pk})
	def __str__ (self):
		return self.album_title+'-'+self.artist
class Song(models.Model):
	album=models.ForeignKey(Album,on_delete=models.CASCADE)
	song_title=models.CharField(max_length=250)
	file_type=models.CharField(max_length=250)
	def __str__ (self):
		return self.song_title

Doc Appointment/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from .models import Speciality,Doctor,Appointment


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class RegisterDoctorForm(ModelForm):
	choices = tuple(Speciality.objects.all().values_list())
	speciality = forms.ChoiceField(choices=choices)

	class Meta:
		model = Doctor
        exclude = ['speciality']

Doc Appointment/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Appointment
from .models import Speciality
from django.views.generic.edit import FormView ,CreateView,DetailView,DeleteView ,ListView,
from django.views.generic.edit import UpdateView
from django.views.generic import Views
from django.contrib import messages
from forms import RegisterDoctorForm
from django.contrib.auth.models import User
from forms import UserForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

def index(request):
    return HttpResponse("Hey check this out")


class CreateAppointment(CreateView):
	template_name = 'appointment_form.html'
	model = Appointment
	fields = '__all__'
	success_url = '/'

	def form_valid(self, form):
		form.save()
		return super(CreateAppointment, self).form_valid(form)

create_appointment = CreateAppointment.as_view()

class RegisterDoctor(CreateView):
	template_name = 'doctor_form.html'
	form_class = RegisterDoctorForm
	success_url = '/'

	def form_valid(self, form):
		form.save()
		return super(RegisterDoctor, self).form_valid(form)

register_doctor = RegisterDoctor.as_view()

class RegisterSpeciality(CreateView):
	template_name = 'specialty_form.html'
	model = Speciality
	fields = '__all__'
	success_url = '/'

	def form_valid(self, form):
		form.save()
		return super(RegisterSpecialty, self).form_valid(form)

register_specialty = RegisterSpecialty.as_view()

class AppointmentList(ListView):
	model = Appointment
	template_name = 'ListAppointment.html'
	def get_context_data(self, **kwargs):
		context = super(AppointmentList, self).get_context_data(**kwargs)
		return context
appointment_list = AppointmentList.as_view()

def AddingUser(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            messages.info(request, "You are now registered and logged in.")
            login(request, new_user)
            return HttpResponseRedirect('/')
    else:
        form = UserForm()

    return render(request, 'adduser.html', {'form': form})

class AppointmentEdit(UpdateView):
	model = Appointment
	template_name = "appointment_form.html"
	success_url = reverse_lazy('appointment_list')
	fields = '__all__'
	def get_object(self, queryset=None):
		obj = super(AppointmentEdit, self).get_object()
		return obj

appointment_edit = AppointmentEdit.as_view()

class AppointmentDelete(DeleteView):
	model = Appointment
	template_name = "appointment_delete.html"
	success_url = reverse_lazy('appointment_list')
	def get_object(self, queryset=None):
		obj = super(AppointmentDelete, self).get_object()
		return obj

appointment_delete = AppointmentDelete.as_view()

Proj/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render,redirect,reverse
from django.views.generic import View
from.models import Album
from django.views import generic

class IndexView(generic.ListView):
	template_name='Proj/index.html'
	context_object_name='all_albums'
	def get_queryset(self):
	 	return Album.objects.all()
class DetailView(generic.DetailView):
    model=Album
    template_name='Proj/detail.html'	
class AlbumCreate(CreateView):
    model=Album 	
    fields=['artist','album_title','genre','album_logo']
class AlbumUpdate(UpdateView):
	model=Album
	fields=['artist','album_title','genre','album_logo']
class AlbumDelete(DeleteView):
	model=Album
	def get_success_url(self):
		return reverse('Proj:index')


Doc Appointment/templates/Docs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Docs Appointment{% endblock %}</title>

    <link rel="stylesheet" type="text/css">
    <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Doctors </a>
          <a class="dropdown-item" href="#">User</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Appointment</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

Proj/templates/Proj/album_form.html
{% extends 'Proj/base.html'%}
{% block title%}Add a New Album{% endblock%}
{% block albums_active%}active{% endblock%}
{% block body %}
 
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-md-7">
				<div class="panel panel-default">
					<div class="panel-body">
						<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{%csrf_token%}
						{% include 'Proj/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
					</div>
					
				</div>
				
			</div>

		</div>
	</div>
</div>
{% endblock%}

Proj/templates/Proj/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Musiq{% endblock %}</title>
   
    <link rel="stylesheet" type="text/css">
    <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button"class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
            <a class="navbar-brand" href="{% url 'Proj:index' %}">Korir</a> 
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                 <li class="active">
                    <a href="{% url 'Proj:album-add' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                    </a>
                 </li>
                 <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                    </a>
                 </li>
            </ul>
        
               <ul class="nav navbar-nav navbar-right ">
                 <li class="">
                    <a href="{% url 'Proj:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
                    </a>
                 </li>
                
            </ul>
       </div>
    </div>
 </nav>
 {% block body %}
 {% endblock%}
</body>
</html>


Proj/templates/Proj/detail.html
{% extends 'Proj/base.html'%}
{% block title %}Album Details{% endblock %}
{% block body %}

      <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'Proj:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                     <form action="{% url 'Proj:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                            <a href="{% url 'Proj:album-update' album.id %}" class="btn btn-primary btn-sm" role="button">Update</a>
                </div>
            </div>
        </div>
	
	    	
	    {% endblock%}
	   

Proj/templates/Proj/form-template.html
{% for field in form %}
<div class-form group>
  <div class="col-sm-offset-2 col-sm-10"> 
  <span class="text-danger small">{{field.errors}}</span>
  
  <label class="control-label col-sm-2">{{ field.label_tag}}</label>
  <div class="col-sm-offset-2 col-sm-10">{{field}}</div>
   </div>
   
</div>
{% endfor %}

Proj/templates/Proj/index.html
 {% extends 'Proj/base.html'%}
{% block body %}
<h3>Here  are all my albums </h3>

	

{% for album in object_list %}
<div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'Proj:detail' album.id %}">
                        <img src="{{ album.album_logo.url }}" class="img-responsive">
                    </a>
                    {% if album.album_logo %}

                          
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>
{% endfor %}
{% endblock%}